# Generated by Django 6.1.1 on 2026-10-05 13:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã ngân sách')),
                ('department', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('cost_center', models.CharField(max_length=50, verbose_name='Trung tâm chi phí')),
                ('name', models.CharField(max_length=255, verbose_name='Tên ngân sách')),
                ('fiscal_year', models.IntegerField(default=2026, verbose_name='Năm tài chính')),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ngân sách cấp')),
                ('committed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đã cam kết/chi')),
            ],
        ),
        migrations.CreateModel(
            name='PriceReference',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã tra cứu')),
                ('label', models.CharField(max_length=255, verbose_name='Tên sản phẩm tham chiếu')),
                ('keywords', models.JSONField(default=list, verbose_name='Từ khóa tra cứu')),
                ('avg_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Giá trung bình lịch sử')),
                ('samples', models.IntegerField(default=10, verbose_name='Số lượng mẫu')),
                ('period', models.CharField(default='6 tháng', max_length=50, verbose_name='Kỳ tham chiếu')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã Nhà cung cấp')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Nhà cung cấp')),
                ('tax_code', models.CharField(blank=True, max_length=50, verbose_name='Mã số thuế')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Người liên hệ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Số điện thoại')),
                ('categories', models.JSONField(default=list, verbose_name='Danh mục cung cấp')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('role', models.CharField(choices=[('employee', 'Employee (Nhân viên)'), ('manager', 'Manager (Quản lý)'), ('procurement', 'Procurement (Thu mua)'), ('finance', 'Finance (Tài chính)'), ('admin', 'Admin (Quản trị)')], default='employee', max_length=20, verbose_name='Vai trò')),
                ('department', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Chức danh')),
                ('locked', models.BooleanField(default=False, verbose_name='Bị khóa')),
                ('can_receive', models.BooleanField(default=True, verbose_name='Có quyền nhận hàng')),
                ('language', models.CharField(default='vi', max_length=10, verbose_name='Ngôn ngữ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã Audit Log')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('actor_name', models.CharField(max_length=150, verbose_name='Tên người thực hiện')),
                ('role', models.CharField(max_length=20, verbose_name='Vai trò')),
                ('action', models.CharField(max_length=100, verbose_name='Hành động')),
                ('entity', models.CharField(max_length=50, verbose_name='Thực thể')),
                ('entity_id', models.CharField(max_length=50, verbose_name='ID thực thể')),
                ('from_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái cũ')),
                ('to_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái mới')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Chi tiết')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã PR')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề yêu cầu')),
                ('justification', models.TextField(blank=True, verbose_name='Lý do/Mục đích mua sắm')),
                ('department', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('cost_center', models.CharField(max_length=50, verbose_name='Trung tâm chi phí')),
                ('category', models.CharField(max_length=100, verbose_name='Danh mục sản phẩm')),
                ('budget_code', models.CharField(max_length=50, verbose_name='Mã ngân sách')),
                ('required_by', models.DateField(blank=True, null=True, verbose_name='Ngày cần hàng')),
                ('delivery_location', models.CharField(blank=True, max_length=255, verbose_name='Địa điểm giao hàng')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('pending_manager', 'Chờ Trưởng phòng duyệt'), ('revision', 'Yêu cầu điều chỉnh'), ('finance_review', 'Chờ Finance duyệt'), ('rejected', 'Bị từ chối'), ('approved', 'Đã phê duyệt (Chờ thu mua)'), ('supplier_selected', 'Đã chọn Nhà cung cấp'), ('po_created', 'Đã tạo Đơn mua hàng (PO)'), ('partially_received', 'Nhận hàng một phần'), ('received', 'Đã nhận đủ hàng'), ('closed', 'Đã đóng (Closed)')], default='draft', max_length=30, verbose_name='Trạng thái')),
                ('routed_to_finance', models.BooleanField(default=False, verbose_name='Chuyển Finance duyệt')),
                ('ai_review', models.CharField(choices=[('none', 'Chưa dùng AI'), ('accepted', 'Đã chấp nhận gợi ý AI'), ('edited', 'Đã sửa lại gợi ý AI'), ('dismissed', 'Bỏ qua AI')], default='none', max_length=20, verbose_name='Trạng thái AI Review')),
                ('last_reason', models.TextField(blank=True, null=True, verbose_name='Lý do gần nhất')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('selected_quotation_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Báo giá được chọn')),
                ('selection_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú chọn Supplier')),
                ('po_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID PO liên kết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã PO')),
                ('quotation_id', models.CharField(max_length=50, verbose_name='ID Báo giá')),
                ('lines', models.JSONField(default=list, verbose_name='Danh sách mặt hàng')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Thuế VAT')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phí giao hàng')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng giá trị PO')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Ngày giao hàng dự kiến')),
                ('status', models.CharField(choices=[('issued', 'Đã phát hành'), ('partially_received', 'Nhận hàng một phần'), ('received', 'Đã nhận đủ hàng'), ('closed', 'Đã đóng (Closed)')], default='issued', max_length=30, verbose_name='Trạng thái PO')),
                ('reconciled', models.BooleanField(default=False, verbose_name='Đã đối soát 3 bên')),
                ('reconciled_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người đối soát')),
                ('reconcile_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú đối soát')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo PO')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='procurement.purchaserequest', verbose_name='Purchase Request')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='procurement.supplier', verbose_name='Nhà cung cấp')),
            ],
        ),
        migrations.CreateModel(
            name='PRLineItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Mặt hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mặt hàng/dịch vụ')),
                ('specs', models.TextField(blank=True, verbose_name='Thông số kỹ thuật')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('unit', models.CharField(default='cái', max_length=50, verbose_name='Đơn tính')),
                ('est_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá dự kiến')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequest', verbose_name='Purchase Request')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã Receiving Note')),
                ('lines', models.JSONField(default=list, verbose_name='Danh sách mặt hàng thực nhận')),
                ('type', models.CharField(choices=[('full', 'Nhận đủ 100%'), ('partial', 'Nhận một phần'), ('discrepancy', 'Có sai lệch')], default='full', max_length=20, verbose_name='Loại nhận hàng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú tình trạng')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhận hàng')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to='procurement.purchaseorder', verbose_name='Purchase Order')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận hàng')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã Quotation')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Tên tệp báo giá')),
                ('file_type', models.CharField(default='pdf', max_length=20, verbose_name='Loại tệp')),
                ('status', models.CharField(default='extracted', max_length=20, verbose_name='Trạng thái')),
                ('ai_confidence', models.DecimalField(decimal_places=2, default=0.95, max_digits=5, verbose_name='Độ tin cậy AI')),
                ('low_confidence', models.JSONField(default=list, verbose_name='Trường độ tin cậy thấp')),
                ('edited_fields', models.JSONField(default=list, verbose_name='Trường đã chỉnh sửa')),
                ('original', models.JSONField(default=dict, verbose_name='Snapshot dữ liệu gốc')),
                ('lines', models.JSONField(default=list, verbose_name='Chi tiết mặt hàng')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Thuế VAT')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phí vận chuyển')),
                ('delivery_days', models.IntegerField(default=3, verbose_name='Số ngày giao hàng')),
                ('warranty_months', models.IntegerField(default=12, verbose_name='Số tháng bảo hành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.purchaserequest', verbose_name='Purchase Request')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.supplier', verbose_name='Nhà cung cấp')),
            ],
        ),
    ]
